### ISSUE TITLE
[v0.81] Unbekannter Modus beim Lesen eines Tags

### ISSUE THREAD

**Issue by dl9sec** [marc136/tonuino-nfc-tools#11]
Hi,

ich habe einen Tag für v2.1.x mit Modus "Album von-bis" beschrieben.
Wenn ich diesen Tag einlese kommt

Modus 8
Der Modus '8' ist unbekannt.

obwohl der Modus ja eigentlich bekannt sein sollte :-)

**Comment by DoriosDE** [comment]
https://github.com/marc136/tonuino-nfc-tools/blob/715ad40f3dfffc5c20d92754ef1cd1104a618aa6/app/src/main/java/de/mw136/tonuino/ui/ReadActivity.kt#L48

sollte in ` text = if (mode in 1..9) { ` geändert werden (habs jedoch nicht getestet)

**Comment by marc136** [comment]
The problem should be fixed for the next version 0.9.0.
