### ISSUE TITLE
[v0.81] Leseprobleme

### ISSUE THREAD

**Issue by dl9sec** [marc136/tonuino-nfc-tools#12]
Hi,

wenn ich das Telefon (Galaxy S7) für eine Weile auf einer Karte liegen lasse und danach versuche einen Tag zu lesen, reagiert die Software nicht mehr darauf. Wegnehmen und wieder auflegen funktioniert nicht mehr, es wird nichts mehr eingelesen.
Erst, wenn ich NFC aus und wieder einschalte und die Software (über Apps) stoppe und wieder starte,
funktioniert das Einlesen wieder.
Kurz auflegen und wieder herunternehmen funktioniert einwandfrei und immer wieder.

**Comment by marc136** [comment]
Danke für die Fehlermeldung.
Wie lange ist denn "eine Weile", ich habe das an meinem Handy mit 5 Minuten ausprobiert, und wenn ich das Handy wegnehme und dann wieder hin halte, wird die Karte neu eingelesen.

Macht es bei dir einen Unterschied, wenn du nachdem das Handy lange auf der Karte lag zurück zur Startseite der App gehst? Kann dann eine neue Karte gelesen werden?

Hast du eventuell Android Studio oder kannst du eine App installieren, mit der du die logcat logs lesen kannst? Vielleicht finden wir darin einen Fehler, wie die App auf NFC events zugreift.

**Comment by dl9sec** [comment]
Hi,
ich weiß, eine "Weile" ist tatsächlich eine schlecht quantifizierte Zeiteinheit :-D
Ich werde das mal empirisch  versuchen genauer einzugrenzen...

Ich probiere das mit dem ZUrückgehen auf die Startseite in diesem Zug dann auch gleich aus.

Android Studio habe ich leider nicht. Installieren könnte ich alles, was keine Root-Berechtigung braucht...

**Comment by dl9sec** [comment]
Konnte die Zeit leider nicht mehr genauer eingrenzen...
