### ISSUE TITLE
NFC Tags are not read

### ISSUE THREAD

**Issue by bkk87** [marc136/tonuino-nfc-tools#16]
Hi Marc, the App was working very fine for me (and all my Tonuino RFID tags) until I switched to a different Android ROM recently (Lineage OS).

I was wondering how to debug this. The Mifare Classic Tool in F-Droid does read the RFID cards on the new ROM.

Best regards,
Bernhard

![Screenshot_20210710-102921_TonUINO_NFC_Tools](https://user-images.githubusercontent.com/70271327/125157501-ae7b5280-e16b-11eb-85eb-b60a81133712.png)

**Comment by KarenSte** [comment]
Hi,
today I had the same issue.
I use a Google Pixel 4a with LinageOS 18.1.

At the last several month I never had any problems with this constellation.

Kind regards,
Karen

**Comment by KarenSte** [comment]
I just installed Version 0.9.1
And everything was fine again.

**Comment by marc136** [comment]
@KarenSte, which version did you install that gave you problems?

1.0.0#24? Or 1.0.0-RC1#23?

**Comment by KarenSte** [comment]
@marc136 I used the official Version from PlayStore 1.0.0#24

**Comment by marc136** [comment]
I submitted the versions 1.0.0#25 and 1.0.1#26 to Google Play for review, until they get approval you could install them as apk directly from the releases here on github https://github.com/marc136/tonuino-nfc-tools/releases

**Comment by KarenSte** [comment]
Now it's working on 1.0.0#26. Thank you for the fast support.

**Comment by bkk87** [comment]
If you say it is working then I will close this issue. I am no longer using TonUINO but only ESPuino.
