### ISSUE TITLE
Gelesene Daten werden nach Änderung falsch geschrieben

### ISSUE THREAD

**Issue by dl9sec** [marc136/tonuino-nfc-tools#9]
Hi,

ich verwende derzeit den Modus "Admin", um die Karte mit Modus 8 (Album Spezial-von-bis) beschreiben zu können. Dabei ist mir aufgefallen, dass beim Zurücklesen und Editieren der Kartendaten, zwar die richtigen Daten angezeigt, jedoch der Modus falsch geschrieben wird.

Folgender Ablauf zur Reproduktion:

1. "TAGS EINZELN EINGEBEN" wählen
2. "Tonuino 2.1" wählen
3. Normal -> Modus "Admin" wählen
4. Auf Tab "Erweitert" -> Ordner 1/Modus 8/Extra 1/Extra2 10 einstellen
5. "Daten auf Tag ... schreiben"

Lesen des Tags -> Alle Daten stimmen

5. "BEARBEITEN" wählen

6. "Tonuino 2.1" wählen
7. Normal -> Modus "Admin" wählen
8. Auf Tab "Erweitert"

Nun stehen die zuvor geschriebenen und zurückgelesenen Daten korrekt da.

9. Wert Extra auf 2 ändern

10.  "Daten auf Tag ... schreiben"

Wenn nun der Tag gelesen wird, steht der Modus auf 6 statt auf 8.

Ich denke, das hängt damit zusammen, dass die zurückgelesene Version beim Editieren nicht gleich eingestellt wird, sondern per default auf "Tonuino 2.0.x" steht und damit im Hintergrund der Modus auf maximal 6 gesetzt wird, das Admin-Feld aber nicht aktualisiert wird.

Ich hoffe, das ist einigermaßen nachvollziehbar :-)

Gruß, Thorsten

**Comment by marc136** [comment]
Ja, ich glaube ich habs verstanden.
Das müsste eigentlich mit der Änderung in #8 behoben werden. Ich werde es aber auf jeden Fall nochmal vorher testen.

**Comment by marc136** [comment]
Also bei mir tritt das Problem mit v0.8.0 nicht mehr auf.
